#!/usr/bin/env python3
import os
import sys
import shutil

def create_ps3_structure(project_root, build_name):
    """
    Creates the PS3 USRDIR structure for packaging.
    """
    ps3_dir = os.path.join(project_root, "build", "ps3", "pkg")
    usr_dir = os.path.join(ps3_dir, "USRDIR")

    # Create directories
    os.makedirs(usr_dir, exist_ok=True)

    # Binary
    self_path = os.path.join(project_root, f"{build_name}.self")
    if os.path.exists(self_path):
        shutil.copy2(self_path, os.path.join(usr_dir, "EBOOT.BIN"))
        print(f"Copied {build_name}.self to USRDIR/EBOOT.BIN")
    else:
        print(f"Warning: {self_path} not found. Did you build it?")

    # Assets (we would copy pre-converted textures here)
    # Example:
    # assets_src = os.path.join(project_root, "build", "ps3", "assets")
    # if os.path.exists(assets_src):
    #     shutil.copytree(assets_src, os.path.join(usr_dir, "assets"), dirs_exist_ok=True)

    # Placeholder for PARAM.SFO and ICON0.PNG
    # In a real PSL1GHT environment, these are generated by other tools.

    print(f"\nPS3 Package structure is ready at: {ps3_dir}")

if __name__ == "__main__":
    root = "."
    name = "sa2"
    if len(sys.argv) > 1: root = sys.argv[1]
    if len(sys.argv) > 2: name = sys.argv[2]

    create_ps3_structure(root, name)
